spring:
  application:
    name: collector

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

# ДОБАВЛЯЕМ gRPC конфигурацию
grpc:
  server:
    port: 9090

# УБИРАЕМ server.port так как теперь используем gRPC порт

logging:
  level:
    ru.yandex.practicum: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"